### ISSUE TITLE
Support for multiple databases

### ISSUE THREAD

**Issue by akaskela** [mikefactorial/SqlVirtualEntityDataProvider#4]
Awesome solution. Could you add support for multiple DBs/connection strings?

**Comment by mikefactorial** [comment]
Good call @akaskela not something I thought about before. I'll take a look at adding support.

**Comment by mikefactorial** [comment]
Shouldn't be that difficult

**Comment by mikefactorial** [comment]
I tested this and is possible without any updates to the provider. You can create a new SQL Provider record with it's own connection string and select it as the Data Source when configuring your virtual entity.
![Config](https://user-images.githubusercontent.com/42348035/99472583-ee5ca380-2916-11eb-8020-fdfdee836574.png)
![sqlproviders](https://user-images.githubusercontent.com/42348035/99472584-eef53a00-2916-11eb-96f8-b9d9d2018a63.png)
